platform:ios,'10.1'

target'WULIU_iOS'do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh', '~> 3.1.12'
pod 'ReactiveCocoa', '~> 2.5'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'TZImagePickerController', '~> 1.8.7'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'Toast'
pod 'MJCSegmentInterface'
pod 'FMDB'
pod 'JPush'
pod 'ActionSheetPicker-3.0'

end

